list: $/city/map/models/marker/columns.yaml
modelClass: City\Map\Models\Marker
title: 'city.map::lang.markers.menu_label'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'city/map/markers/update/:id'
